package Kinematics.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  private final Map<SConceptId, Integer> myIndexMap = new HashMap<SConceptId, Integer>(6);
  /*package*/ final ConceptDescriptor myConceptKinematicChain = new ConceptDescriptorBuilder("Kinematics.structure.KinematicChain", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210246dfL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(0x3f167204210246e2L, "baseLink", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178bcL), false), new ConceptDescriptorBuilder.Ref(0x3f167204210246e9L, "tipLink", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178bcL), false)).references("baseLink", "tipLink").sourceNode(new SNodePointer("r:cd13618c-02ad-4af8-a3e4-3414c58c4613(Kinematics.structure)", "4545946235936327391")).create();
  /*package*/ final ConceptDescriptor myConceptOrigin = new ConceptDescriptorBuilder("Kinematics.structure.Origin", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178e0L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3f1672042101943eL, "Rr"), new ConceptDescriptorBuilder.Prop(0x3f167204210178e3L, "Rp"), new ConceptDescriptorBuilder.Prop(0x3f167204210178e6L, "Ry"), new ConceptDescriptorBuilder.Prop(0x3f16720421019446L, "Px"), new ConceptDescriptorBuilder.Prop(0x3f1672042101944bL, "Py"), new ConceptDescriptorBuilder.Prop(0x3f16720421019451L, "Pz")).properties("Rr", "Rp", "Ry", "Px", "Py", "Pz").sourceNode(new SNodePointer("r:cd13618c-02ad-4af8-a3e4-3414c58c4613(Kinematics.structure)", "4545946235936274656")).create();
  /*package*/ final ConceptDescriptor myConceptRobotJoint = new ConceptDescriptorBuilder("Kinematics.structure.RobotJoint", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178bbL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3f167204210178deL, "type"), new ConceptDescriptorBuilder.Prop(0x3f16720421019465L, "stiffness")).properties("type", "stiffness").referenceDescriptors(new ConceptDescriptorBuilder.Ref(0x3f16720421019461L, "child", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178bcL), true), new ConceptDescriptorBuilder.Ref(0x3f1672042101945eL, "parent", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178bcL), true)).references("child", "parent").childDescriptors(new ConceptDescriptorBuilder.Link(0x3f16720421019458L, "origin", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178e0L), true, false, false)).children(new String[]{"origin"}, new boolean[]{false}).sourceNode(new SNodePointer("r:cd13618c-02ad-4af8-a3e4-3414c58c4613(Kinematics.structure)", "4545946235936274619")).create();
  /*package*/ final ConceptDescriptor myConceptRobotLink = new ConceptDescriptorBuilder("Kinematics.structure.RobotLink", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178bcL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3f16720421019497L, "interial", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f1672042101946aL), true, false, false)).children(new String[]{"interial"}, new boolean[]{false}).sourceNode(new SNodePointer("r:cd13618c-02ad-4af8-a3e4-3414c58c4613(Kinematics.structure)", "4545946235936274620")).create();
  /*package*/ final ConceptDescriptor myConceptRobotLinkInertial = new ConceptDescriptorBuilder("Kinematics.structure.RobotLinkInertial", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f1672042101946aL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3f16720421019474L, "mass"), new ConceptDescriptorBuilder.Prop(0x3f16720421019476L, "ixx"), new ConceptDescriptorBuilder.Prop(0x3f16720421019479L, "ixy"), new ConceptDescriptorBuilder.Prop(0x3f1672042101947dL, "ixz"), new ConceptDescriptorBuilder.Prop(0x3f16720421019482L, "iyy"), new ConceptDescriptorBuilder.Prop(0x3f16720421019488L, "iyz"), new ConceptDescriptorBuilder.Prop(0x3f1672042101948fL, "izz")).properties("mass", "ixx", "ixy", "ixz", "iyy", "iyz", "izz").childDescriptors(new ConceptDescriptorBuilder.Link(0x3f1672042101946bL, "origin", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178e0L), true, false, false)).children(new String[]{"origin"}, new boolean[]{false}).sourceNode(new SNodePointer("r:cd13618c-02ad-4af8-a3e4-3414c58c4613(Kinematics.structure)", "4545946235936281706")).create();
  /*package*/ final ConceptDescriptor myConceptRobotModel = new ConceptDescriptorBuilder("Kinematics.structure.RobotModel", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178baL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3f16720421019499L, "origin", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178e0L), true, false, false), new ConceptDescriptorBuilder.Link(0x3f1672042101949bL, "joints", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178bbL), true, true, false), new ConceptDescriptorBuilder.Link(0x3f1672042101949eL, "links", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210178bcL), true, true, false), new ConceptDescriptorBuilder.Link(0x3f167204210246e4L, "chains", MetaIdFactory.conceptId(0xd6881f78a85d4c9eL, 0x931e30879e67afddL, 0x3f167204210246dfL), true, true, false)).children(new String[]{"origin", "joints", "links", "chains"}, new boolean[]{false, true, true, true}).sourceNode(new SNodePointer("r:cd13618c-02ad-4af8-a3e4-3414c58c4613(Kinematics.structure)", "4545946235936274618")).create();

  public StructureAspectDescriptor() {
    myIndexMap.put(myConceptKinematicChain.getId(), 0);
    myIndexMap.put(myConceptOrigin.getId(), 1);
    myIndexMap.put(myConceptRobotJoint.getId(), 2);
    myIndexMap.put(myConceptRobotLink.getId(), 3);
    myIndexMap.put(myConceptRobotLinkInertial.getId(), 4);
    myIndexMap.put(myConceptRobotModel.getId(), 5);
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptKinematicChain, myConceptOrigin, myConceptRobotJoint, myConceptRobotLink, myConceptRobotLinkInertial, myConceptRobotModel);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    Integer index = myIndexMap.get(id);
    if (index == null) {
      return null;
    }
    switch (((int) index)) {
      case 0:
        return myConceptKinematicChain;
      case 1:
        return myConceptOrigin;
      case 2:
        return myConceptRobotJoint;
      case 3:
        return myConceptRobotLink;
      case 4:
        return myConceptRobotLinkInertial;
      case 5:
        return myConceptRobotModel;
      default:
        throw new IllegalStateException();
    }
  }
}
